services:
  # PostgreSQL database
  postgres-db:
    image: postgres:alpine
    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: spring_boot_starter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  # Spring Boot application
  spring-boot-starter:
    image: ericus20/spring-boot-starter:latest

    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "8080:8080"

    depends_on:
      postgres-db:
        condition: service_healthy

    environment:
      SPRING_PROFILES_ACTIVE: docker

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/spring_boot_starter
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8080/actuator/health | grep UP || exit 1"
        ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s


volumes:
  postgres-data: